<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMDxXlml\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMDxXlml/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMDxXlml.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMDxXlml\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMDxXlml\App_KernelDevDebugContainer([
    'container.build_hash' => 'MDxXlml',
    'container.build_id' => '15559b5a',
    'container.build_time' => 1752823199,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMDxXlml');
